//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Services.TadenorService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicePXSoap", Namespace="http://www.pagoexpress.com.mx/ServicePX")]
    public partial class ServicePX : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StatusPTVAndOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfInicialAndOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoDisponibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReloadClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getReverseClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQueryClassOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQueryDatClassOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicePX() {
            this.Url = global::Services.Properties.Settings.Default.Services_TadenorService_ServicePX;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StatusPTVAndCompletedEventHandler StatusPTVAndCompleted;
        
        /// <remarks/>
        public event ConfInicialAndCompletedEventHandler ConfInicialAndCompleted;
        
        /// <remarks/>
        public event SaldoDisponibleCompletedEventHandler SaldoDisponibleCompleted;
        
        /// <remarks/>
        public event getReloadClassCompletedEventHandler getReloadClassCompleted;
        
        /// <remarks/>
        public event getReloadDataCompletedEventHandler getReloadDataCompleted;
        
        /// <remarks/>
        public event getReverseClassCompletedEventHandler getReverseClassCompleted;
        
        /// <remarks/>
        public event getQueryClassCompletedEventHandler getQueryClassCompleted;
        
        /// <remarks/>
        public event getQueryDatClassCompletedEventHandler getQueryDatClassCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/StatusPTVAnd", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StatusPTVAnd(string sXML) {
            object[] results = this.Invoke("StatusPTVAnd", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StatusPTVAndAsync(string sXML) {
            this.StatusPTVAndAsync(sXML, null);
        }
        
        /// <remarks/>
        public void StatusPTVAndAsync(string sXML, object userState) {
            if ((this.StatusPTVAndOperationCompleted == null)) {
                this.StatusPTVAndOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatusPTVAndOperationCompleted);
            }
            this.InvokeAsync("StatusPTVAnd", new object[] {
                        sXML}, this.StatusPTVAndOperationCompleted, userState);
        }
        
        private void OnStatusPTVAndOperationCompleted(object arg) {
            if ((this.StatusPTVAndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatusPTVAndCompleted(this, new StatusPTVAndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/ConfInicialAnd", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfInicialAnd(string sXML) {
            object[] results = this.Invoke("ConfInicialAnd", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfInicialAndAsync(string sXML) {
            this.ConfInicialAndAsync(sXML, null);
        }
        
        /// <remarks/>
        public void ConfInicialAndAsync(string sXML, object userState) {
            if ((this.ConfInicialAndOperationCompleted == null)) {
                this.ConfInicialAndOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfInicialAndOperationCompleted);
            }
            this.InvokeAsync("ConfInicialAnd", new object[] {
                        sXML}, this.ConfInicialAndOperationCompleted, userState);
        }
        
        private void OnConfInicialAndOperationCompleted(object arg) {
            if ((this.ConfInicialAndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfInicialAndCompleted(this, new ConfInicialAndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/SaldoDisponible", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double SaldoDisponible(long lGrupo, long lCadena, long lTienda) {
            object[] results = this.Invoke("SaldoDisponible", new object[] {
                        lGrupo,
                        lCadena,
                        lTienda});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoDisponibleAsync(long lGrupo, long lCadena, long lTienda) {
            this.SaldoDisponibleAsync(lGrupo, lCadena, lTienda, null);
        }
        
        /// <remarks/>
        public void SaldoDisponibleAsync(long lGrupo, long lCadena, long lTienda, object userState) {
            if ((this.SaldoDisponibleOperationCompleted == null)) {
                this.SaldoDisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoDisponibleOperationCompleted);
            }
            this.InvokeAsync("SaldoDisponible", new object[] {
                        lGrupo,
                        lCadena,
                        lTienda}, this.SaldoDisponibleOperationCompleted, userState);
        }
        
        private void OnSaldoDisponibleOperationCompleted(object arg) {
            if ((this.SaldoDisponibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoDisponibleCompleted(this, new SaldoDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/getReloadClass", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getReloadClass(string sXML) {
            object[] results = this.Invoke("getReloadClass", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getReloadClassAsync(string sXML) {
            this.getReloadClassAsync(sXML, null);
        }
        
        /// <remarks/>
        public void getReloadClassAsync(string sXML, object userState) {
            if ((this.getReloadClassOperationCompleted == null)) {
                this.getReloadClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReloadClassOperationCompleted);
            }
            this.InvokeAsync("getReloadClass", new object[] {
                        sXML}, this.getReloadClassOperationCompleted, userState);
        }
        
        private void OngetReloadClassOperationCompleted(object arg) {
            if ((this.getReloadClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReloadClassCompleted(this, new getReloadClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/getReloadData", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getReloadData(string sXML) {
            object[] results = this.Invoke("getReloadData", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getReloadDataAsync(string sXML) {
            this.getReloadDataAsync(sXML, null);
        }
        
        /// <remarks/>
        public void getReloadDataAsync(string sXML, object userState) {
            if ((this.getReloadDataOperationCompleted == null)) {
                this.getReloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReloadDataOperationCompleted);
            }
            this.InvokeAsync("getReloadData", new object[] {
                        sXML}, this.getReloadDataOperationCompleted, userState);
        }
        
        private void OngetReloadDataOperationCompleted(object arg) {
            if ((this.getReloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReloadDataCompleted(this, new getReloadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/getReverseClass", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getReverseClass(string sXML) {
            object[] results = this.Invoke("getReverseClass", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getReverseClassAsync(string sXML) {
            this.getReverseClassAsync(sXML, null);
        }
        
        /// <remarks/>
        public void getReverseClassAsync(string sXML, object userState) {
            if ((this.getReverseClassOperationCompleted == null)) {
                this.getReverseClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetReverseClassOperationCompleted);
            }
            this.InvokeAsync("getReverseClass", new object[] {
                        sXML}, this.getReverseClassOperationCompleted, userState);
        }
        
        private void OngetReverseClassOperationCompleted(object arg) {
            if ((this.getReverseClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getReverseClassCompleted(this, new getReverseClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/getQueryClass", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getQueryClass(string sXML) {
            object[] results = this.Invoke("getQueryClass", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getQueryClassAsync(string sXML) {
            this.getQueryClassAsync(sXML, null);
        }
        
        /// <remarks/>
        public void getQueryClassAsync(string sXML, object userState) {
            if ((this.getQueryClassOperationCompleted == null)) {
                this.getQueryClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQueryClassOperationCompleted);
            }
            this.InvokeAsync("getQueryClass", new object[] {
                        sXML}, this.getQueryClassOperationCompleted, userState);
        }
        
        private void OngetQueryClassOperationCompleted(object arg) {
            if ((this.getQueryClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQueryClassCompleted(this, new getQueryClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pagoexpress.com.mx/ServicePX/getQueryDatClass", RequestNamespace="http://www.pagoexpress.com.mx/ServicePX", ResponseNamespace="http://www.pagoexpress.com.mx/ServicePX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getQueryDatClass(string sXML) {
            object[] results = this.Invoke("getQueryDatClass", new object[] {
                        sXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getQueryDatClassAsync(string sXML) {
            this.getQueryDatClassAsync(sXML, null);
        }
        
        /// <remarks/>
        public void getQueryDatClassAsync(string sXML, object userState) {
            if ((this.getQueryDatClassOperationCompleted == null)) {
                this.getQueryDatClassOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQueryDatClassOperationCompleted);
            }
            this.InvokeAsync("getQueryDatClass", new object[] {
                        sXML}, this.getQueryDatClassOperationCompleted, userState);
        }
        
        private void OngetQueryDatClassOperationCompleted(object arg) {
            if ((this.getQueryDatClassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQueryDatClassCompleted(this, new getQueryDatClassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void StatusPTVAndCompletedEventHandler(object sender, StatusPTVAndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StatusPTVAndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatusPTVAndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ConfInicialAndCompletedEventHandler(object sender, ConfInicialAndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfInicialAndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfInicialAndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SaldoDisponibleCompletedEventHandler(object sender, SaldoDisponibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoDisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoDisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getReloadClassCompletedEventHandler(object sender, getReloadClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReloadClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReloadClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getReloadDataCompletedEventHandler(object sender, getReloadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReloadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReloadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getReverseClassCompletedEventHandler(object sender, getReverseClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getReverseClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getReverseClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getQueryClassCompletedEventHandler(object sender, getQueryClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQueryClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQueryClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void getQueryDatClassCompletedEventHandler(object sender, getQueryDatClassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQueryDatClassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQueryDatClassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591